version: "3.8"

services: &default-services
  gem: &base
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app

  test:
    <<: *base
    command: rake spec

  lint:
    <<: *base
    command: rake rubocop
