version: "3.9"

services: &default-services
  gem: &base
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - .:/usr/src/app

  test:
    <<: *base
    command: rake spec

  lint:
    <<: *base
    command: rake rubocop

  deploy:
    <<: *base
    command: ./bin/actions-deploy-gem
    environment:
      GH_TOKEN: $GH_TOKEN
